assignment2/friendface/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/* This is the root route.  It simply renders the home page using a query of all entries from
the posts database, mashed with matching comments for the purposes of a count only*/
Route::get('/', array('as' => 'post.index', 'uses' => 'PostController@index'));

/* This route gets all the comments associated with a given post
and renders the comments view */
Route::get('/comments/{postId}', array('as'=>"comments", 'uses' => 'CommentController@index'));
Route::get('/comments/delete/{id}', array('as'=>"comments.delete", 'uses' => 'CommentController@destroy'));
Route::resource('comments', 'CommentController');

Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
Route::resource('user', 'UserController');
Route::get('/post/delete/{id}', array('as' => 'post.delete', 'uses' => 'PostController@destroy'));
Route::resource('post', 'PostController');

Route::resource('friend', 'FriendController');


/* This route redirects to the confirmation page.  It is used as confirmation of delete, which then
redirects to the route which actually performs the redirect.*/
Route::get('/confirmdeletepost/{id}', array('as'=>"confirmdeletepost", function($id)
{
    // get the post in question so that we can display some information about it on the confirmation page
    $post = Post::find($id);
    return View::make('confirm')
        ->withTitle("Are you sure you want to delete this post?")
        ->withDescription($post->user->full_name.': '.$post->content)
        ->withConfirmurl(url('/post/delete/'.$post->id))
        ->withCancelurl(url('/'))
        ->withOklabel('Delete')
        ->withCancellabel('Cancel');
}));

/* This route redirects to the confirmation page for comment deletion,
the actual deletion is done on another page */
Route::get('/confirmdeletecomment/{id}', array('as'=>"confirmdeletecomment", function($id)
{
    // get the comment so we can display some information about it on the confirmation page.
    $comment = Comment::find($id);
    return View::make('confirm')
        ->withTitle("Are you sure you want to delete this comment?")
        ->withDescription($comment->user->full_name.': '.$comment->content)
        ->withConfirmurl(url('/comments/delete/'.($comment->id)))
        ->withCancelurl(url('/comments/'.$comment->post->id))
        ->withOklabel('Delete')
        ->withCancellabel('Cancel');
}));

/* Route to display the documentation */
Route::get('/documentation', array('as'=>"documentation", function()
{
    return View::make('documentation');
}));

assignment2/friendface/app/views/comments.blade.php
@extends("layout")

@section('content')

    <div class="col-md-8 chat-window">
        <div class="panel panel-default">
            <div class="panel-heading top-bar">
                <div class = "pull-right">{{ $comments->links() }}</div>
                <div class="col-md-8 col-xs-8">
                    <h3 class="panel-title pull-left" style="padding-bottom: 10px;"><span class="glyphicon glyphicon-comment"></span> Comments</h3>
                </div>
                @if(Auth::check())
                <form action="{{{url("/comments")}}}" method="post">
                    <input type="hidden" name="postId" value="{{{$post->id}}}">
                    <div class="input-group" style="margin: 10px; width: 95%">
                        <input id="messageInput" name="messageInput" class="form-control input-sm chat_input" placeholder="Write your comment here..." type="text">
                        <span class="input-group-btn">
                            <input type="submit" class="btn btn-primary btn-sm" id="btn-chat" value="Submit Comment">
                        </span>
                    </div>
                </form>
                @endif
            </div>
            <div class="panel-body msg_container_base">
                <!-- ICON ON LEFT -->
                <div class="row msg_container base_receive">
                    <div class="col-md-2 col-xs-2 avatar">
                        <!-- img src="http://www.bitrebels.com/wp-content/uploads/2011/02/Original-Facebook-Geek-Profile-Avatar-1.jpg" class=" img-responsive " -->
                        <img src="{{ asset($post->user->profile_image->url('medium')) }}" class=" img-responsive ">

                    </div>
                    <div class="col-md-10 col-xs-10">
                        <div class="messages msg_receive">
                            <b>{{{$post->title}}}</b>
                            <p>{{{$post->content}}}</p>
                            <time datetime="2009-11-13T20:00">{{{$post->user->full_name}}} • <span id="datespanPost">{{{$post->created_at}}}</span>
                            </time>
                        </div>
                    </div>
                </div>
                <!-- This function will format the given date/time and place it in the element with the given id -->
                <script>formatLocalTime("{{{$post->created_at}}}", "datespanPost");</script>
                @foreach($comments as $comment)
                        <!-- ICON ON RIGHT -->
                <div class="row msg_container base_sent">
                    <div class="col-md-10 col-xs-10">
                        <div class="messages msg_sent">
                            <p>{{{$comment->content}}}</p>
                            <time datetime="{{{$comment->created_at}}}">{{{$comment->user->full_name}}} • <span id="datespan{{{$post->id}}}">{{{$comment->created_at}}}</span></time>
                            @if(Auth::check() && Auth::user()->id == $comment->user->id)
                                <a href="{{{url("/confirmdeletecomment/".$comment->id)}}}" class="pull-left text-danger"><i class="glyphicon glyphicon-remove"></i></a>
                            @endif

                        </div>
                    </div>
                    <div class="col-md-2 col-xs-2 avatar">
                        <!-- img src="http://www.bitrebels.com/wp-content/uploads/2011/02/Original-Facebook-Geek-Profile-Avatar-1.jpg" class=" img-responsive " -->
                        <img src="{{ asset($comment->user->profile_image->url('medium')) }}" class=" img-responsive ">
                    </div>
                </div>
                <!-- This function will format the given date/time and place it in the element with the given id -->
                <script>formatLocalTime("{{{$post->created_at}}}", "datespan{{{$post->id}}}");</script>
                @endforeach
            </div>
            <!--div class="panel-footer">
                <div class="input-group">
                    <input id="btn-input" class="form-control input-sm chat_input" placeholder="Write your message here..." type="text">
                        <span class="input-group-btn">
                        <button class="btn btn-primary btn-sm" id="btn-chat">Send</button>
                        </span>
                </div>
            </div-->
        </div>
    </div>

@stop
@stop

assignment2/friendface/app/views/confirm.blade.php
@extends("layout")
@section('content')

    <div class="row">
        <div class="span12">
            <div class="hero-unit center">
                <h3>{{{$title}}}</h3>
                <br>
                <p>{{{$description}}}</p>
                <a href="{{{$confirmurl}}}" class="btn btn-large btn-danger">{{$oklabel}}</a>
                <a href="{{{$cancelurl}}}" class="btn btn-large btn-info">{{$cancellabel}}</a>
            </div>
            <br>
        </div>
    </div>
@stop
@stop

assignment2/friendface/app/views/createuser.blade.php
@extends ("layout")
@section ("content")
    <div class="col-md-8 chat-window">
        <div class="panel panel-default">
            <div class="panel-heading top-bar">
                <b>Create new user</b>
            </div>
            <div class="panel-body" style="padding:20px;">
            {{ Form::open(array('action' => array('UserController@store'), 'files'=>true)) }}
            <div class="form-group">
                {{Form::label('full_name', 'Full Name')}}
                {{Form::text('full_name', Input::old('full_name'), array('placeholder'=>'John Smith'))}}
                <div class="help-block with-errors text-danger">{{$errors->first('full_name')}}</div>
            </div>
                <div class="form-group">
                    {{Form::label('email', 'Email')}}
                    {{Form::email('email', Input::old('email'), array('placeholder'=>'me@example.org'))}}
                    <div class="help-block with-errors text-danger">{{$errors->first('email')}}</div>
                </div>

                <div class="form-group">
                    {{Form::label('date_of_birth', 'Date of Birth')}}
                    {{Form::text('date_of_birth', Input::old('date_of_birth'), array('placeholder'=>'8 November 1979'))}}
                    <div class="help-block with-errors text-danger">{{$errors->first('date_of_birth')}}</div>
                </div>

                <div class="form-group">
                    {{ Form::label('profile_image', 'Profile Image') }}
                    {{ Form::file('profile_image') }}
                    <div class="help-block with-errors text-danger">{{$errors->first('profile_image')}}</div>
                </div>

                <div class="form-group">
                    {{Form::label('password', 'Password')}}
                    {{Form::password('password')}}
                    <div class="help-block with-errors text-danger">{{$errors->first('password')}}</div>
                </div>

                <div class="form-group">
                    {{Form::label('repeat_password', 'Repeat Password')}}
                    {{Form::password('repeat_password')}}
                    <div class="help-block with-errors text-danger">{{$errors->first('repeat_password')}}</div>
                </div>

            {{Form::submit('Submit')}}

            {{Form::close()}}
        </div>
    </div>

@stop
@stop

assignment2/friendface/app/views/documentation.blade.php
@extends("layout")

@section('content')

    <div class="col-md-8 chat-window">
        <div class="panel panel-default">
            <div class="panel-heading top-bar">
                <div class="col-md-8 col-xs-8">
                    <h3 class="panel-title" style="padding-bottom: 10px;"><span class="glyphicon glyphicon-book"></span> Documentation</h3>
                </div>
            </div>
            <div class="panel-body doc_container_base">

                <h3>Project Documetation 2503ICT Assignment 2</h3>
                <h4>Mark Pointing S5006416</h4>
                <h4>ER Diagram for the Social Network Database</h4>
                <img src="/images/EER_Diagram.svg" alt="EER Diagram"/>
                <h4>Features Implemented</h4>
                <p>All required features were implemented, including the following:</p>
                <ul>
                    <li>Navigation menu on all pages</li>
                    <li>Create post form on home page</li>
                    <li>Only create post/comment when logged in (with server side checking)</li>
                    <li>Each post contains an image</li>
                    <li>Each post contains a title, message and name</li>
                    <li>Each post indicates the number of comments</li>
                    <li>Each post has edit and delete links, only available to owner, as well as server side validation of ownership</li>
                    <li>Each post has a view comments link which redirects to a new page, comments are paginated</li>
                    <li>Each comment and post can be edited in a form on a new page</li>
                    <li>Each post has privacy settings which can also be edited</li>
                </ul>

                <h4>Challenges and Interesting Solutions</h4>
                    <p>Foreign keys were implemented in the model with hasMany and belongsToMany functions.  Also cascaded deletion of
                    posts and comments was achieved in the schema with onDelete('cascade').</p>

                <h4>Extra Features</h4>
                    <p>All database operations are validated on the server side, even if client side protection is available.</p>
                    <p>All database delete operations redirect to a confirmation page before carrying out the delete operation.
                    This is designed to protect against inadvertent post or comment deletion.  Add and remove friends displays
                    a confirmation message with Session::flash().</p>
            </div>
        </div>
    </div>

@stop
@stop

assignment2/friendface/app/views/edit.blade.php
@extends("layout")

@section('content')
    <div class="col-md-8 chat-window">
        <div class="panel panel-default">
            <div class="panel-heading top-bar">
                <div class="col-md-8 col-xs-8" style="padding-bottom: 10px;">
                <h3 class="panel-title"><span class="glyphicon glyphicon-edit"></span> Edit Post</h3>
                </div>

                {{ Form::model($post, array('route' => array('post.update', $post->id), 'method' => 'PUT')) }}
                    <div class="input-group" style="padding-bottom:10px;width:100%;">
                        <label for="titleInput">Title</label>
                        <input id="titleInput" name="titleInput" class="form-control input-sm chat_input" placeholder="Title your post..." type="text" value="{{{$post->title}}}">
                    </div>
                    <div class="input-group" style="padding-bottom:10px;width:100%;">
                        <label for="messageInput">Post</label>
                        <textarea id="messageInput" name="messageInput" class="form-control input-sm chat_input" placeholder="Write your message here...">{{{$post->content}}}</textarea>
                    </div>

                    <div class="input-group" style="padding-bottom: 10px;">
                        <select id="privacyInput" name="privacyInput" class="form-control input-sm chat_input" value="">
                            <option value="1" @if($post->privacy == 1) selected @endif >Only my friends can view this post</option>
                            <option value="0" @if($post->privacy == 0) selected @endif >Anyone can view this post</option>
                            <option value="2" @if($post->privacy == 2) selected @endif >Only I can view this post</option>
                        </select>
                    </div>
                    <div class="input-group">
                        <input type="submit" value="Save Changes" class="btn btn-primary btn-sm" id="buttonSubmit">
                        <a href="{{url("/")}}" class="btn btn-default btn-sm" id="buttonCancel">Discard Changes</a>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@stop
@stop

assignment2/friendface/app/views/errorpage.blade.php
@extends("layout")
@section('content')

    <div class="row">
        <div class="span12">
            <div class="hero-unit center">
                <h1>{{{$errortitle}}}</h1>
                <br>
                <p>{{{$errordescription}}}</p>
                <a href="{{{$returnurl}}}" class="btn btn-large btn-info">Ok, got it.  I'll try that again.</a>
            </div>
            <br>
        </div>
    </div>
@stop
@stop

assignment2/friendface/app/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Mark Pointing 2503ICT</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!-- Local Style Sheets -->
    <link href="/css/chatstyle.css" rel="stylesheet">
    <link href="/css/profilestyle.css" rel="stylesheet">
    <link href="/css/loginstyle.css" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">

    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script>
        // a script to convert UTC from the server to localtime, and push it into an element.
        var formatLocalTime = function(utcTime, elementId){
            utcTime = utcTime.replace(" ", "T");
            utcTime += "+00:00";
            console.log(utcTime);
            var myDate = new Date(utcTime);
            var dateString = myDate.toString();
            var pos = dateString.lastIndexOf(":");
            dateString = dateString.substr(0, pos);
            $('#'+elementId).html(dateString);
        }
    </script>

</head>
<body>

<?php
        $today = new DateTime();
        if(Auth::check()){
            if (empty($sidebar_user)){
                $sidebar_user = Auth::user();
            }
            if($sidebar_user->id == Auth::user()->id) {
                $sidebar_user->status = "(You)";
                $sidebar_user->isYou = true;
                $sidebar_user->isFriend = false;
            }
            else if(Friend::where('user_id',"=",Auth::user()->id)->where('friend_id', "=", $sidebar_user->id)->count() ){
                $sidebar_user->status = "Friend";
                $sidebar_user->isYou = false;
                $sidebar_user->isFriend = true;
            }
            else{
                $sidebar_user->status = "FriendFace User";
                $sidebar_user->isYou = false;
                $sidebar_user->isFriend = false;
            }
        }

        if(!empty($sidebar_user)) $sidebar_user->age = $sidebar_user->date_of_birth->diff($today)->y;

?>

<div class="container">
    <!-- --------------------------------------------- -->
    <div class="col-md-4">
        <div class="row profile">
            <div class="profile-sidebar">
                @if (Auth::check() || !empty($sidebar_user))
                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">
                        <!-- img src="http://www.bitrebels.com/wp-content/uploads/2011/02/Original-Facebook-Geek-Profile-Avatar-1.jpg" class=" img-responsive "-->
                        <img src="{{ asset($sidebar_user->profile_image->url('medium')) }}" class=" img-responsive ">
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name">
                            {{$sidebar_user->full_name}}
                        </div>

                        @if(! $sidebar_user->isYou)
                            <div class="profile-usertitle-job">
                                {{$sidebar_user->status}}
                            </div>
                        @endif

                        <div class="profile-usertitle-job">
                            {{$sidebar_user->age}} Years old
                        </div>

                        @if(! $sidebar_user->isYou)

                            @if($sidebar_user->isFriend)
                                {{Form::open(array('action'=>array("FriendController@destroy",$sidebar_user->id)))}}
                                {{ Form::hidden('_method', 'DELETE') }}
                                <input type="submit" class="btn btn-xs btn-danger" value="Remove Friend">
                                {{Form::close()}}
                            @else
                                {{Form::open(array('action'=>"FriendController@store"))}}
                                {{Form::hidden('friend_id', $sidebar_user->id)}}
                                <input type="submit" class="btn btn-xs btn-primary" value="Add Friend">
                                {{Form::close()}}
                            @endif
                        @endif

                    </div>


                @else
                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">
                        <img src="/images/friendface_symbol.png" class=" img-responsive ">
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name">
                            FriendFace
                        </div>
                        <div class="profile-usertitle-job">
                            Welcome to FriendFace
                        </div>
                    </div>
                @endif
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR BUTTONS -->
                <!-- div class="profile-userbuttons">
                    <button type="button" class="btn btn-success btn-sm">Follow</button>
                    <button type="button" class="btn btn-danger btn-sm">Message</button>
                </div -->
                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">

                        <!--li class="active"-->
                        <li class="animated slideInLeft">
                            <a href="/">
                                <i class="glyphicon glyphicon-home"></i>
                                Home </a>
                        </li>

                        <li class="animated slideInLeft">
                            <a href="{{action('UserController@index')}}">
                                <i class="glyphicon glyphicon-search"></i>
                                Find New Friends </a>
                        </li>

                        @if(!empty($sidebar_user))
                        <li class="animated slideInLeft">
                            <a href="{{action('FriendController@show', $sidebar_user->id)}}">
                                <i class="glyphicon glyphicon-user"></i>
                                Show Friends</a>
                        </li>
                        @endif

                            <li class="animated slideInLeft">
                                <a href="{{{url("/documentation")}}}">
                                    <i class="glyphicon glyphicon-book"></i>
                                    Documentation </a>
                            </li>

                        @if (Auth::check())
                            <li class="animated slideInLeft">
                                <a href="{{{route('user.logout', 'Logout')}}}">
                                    <i class="glyphicon glyphicon-log-out"></i>
                                    Log Out</a>
                            </li>

                        @else
                            <li class="dropdown animated slideInLeft">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-log-in"></i><b>Login/Join</b> <span class="caret"></span></a>
                                <ul id="login-dp" class="dropdown-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-md-12">
                                                {{-- Form::open(array('url' => secure_url('user/login'))) --}}
                                                {{ Form::open(array('url' => url('user/login'))) }}
                                                <div class="form-group">
                                                    {{Form::label('email', 'Email', ["class" => "sr-only"])}}
                                                    {{Form::text('email', "",["class"=>"form-control", "placeholder"=>"Email", "required"=>"" ])}}
                                                </div>
                                                <div class="form-group">
                                                    {{Form::label('password', 'Password', ["class" => "sr-only"])}}
                                                    {{Form::password('password', ["class"=>"form-control", "placeholder"=>"Password", "required"=>"" ])}}
                                                </div>

                                                <div class="form-group">
                                                    {{Form::submit('Sign In', array("class" => "btn btn-primary btn-block"))}}
                                                </div>
                                                {{Form::close()}}
                                            </div>
                                            <div class="bottom text-center">
                                                New here ? {{ link_to_route('user.create', 'Join us') }}
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            @if (Session::get('loginError'))
                                <li>
                                    <a href="#"><i class="glyphicon glyphicon-remove-circle text-danger"></i><b class="text-danger">{{ Session::get('loginError') }}</b></a>
                                </li>
                            @endif

                        @endif

                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>
    </div>
    <!-- --------------------------------------------- -->
    <!-- content -->
    @yield('content')
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</body>
</html>

assignment2/friendface/app/views/userlist.blade.php
/**
* Created by PhpStorm.
* User: mark
* Date: 29/05/16
* Time: 10:30 AM
*/
@extends("layout")
@section('content')
    <div class="col-md-8 chat-window">
        @if(Session::get('message'))
            <p class="well" style="background-color: chartreuse;"><b>{{{Session::get('message')}}}</b></p>
        @endif
    {{Form::open(array('action' => 'FriendController@index', 'method'=>'GET'))}}
        <div class="input-group" style="padding-bottom:10px;">
            <input id="searchInput" name="searchInput" class="form-control input-sm chat_input" placeholder="Search friends..." type="text">
                        <span class="input-group-btn">
                            <input type="submit" value="Search" class="btn btn-primary btn-sm">
                        </span>
        </div>
        <!--div class="col-md-8 col-xs-8">
        <h3 class="panel-title"><span class="glyphicon glyphicon-comment"></span> Chat - Miguel</h3>
    </div-->
    {{Form::close()}}

    @foreach ($users as $user)
        <div class="col-md-6">
            <div class="well well-sm" style="min-height:150px;">
                <div class="media">
                    <a class="thumbnail pull-left" href="/user/{{{$user->id}}}">
                        <img class="media-object" src="{{ asset($user->profile_image->url('thumb')) }}">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">{{{$user->full_name}}}</h4>
                        <p>Age: {{{$user->age}}}</p>
                        <p>
                            <a href="/user/{{{$user->id}}}" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-zoom-in"></span> View Profile</a>
                            @if(Auth::check())
                            @if(! $user->isYou)
                                @if($user->isFriend)
                                    {{Form::open(array('action'=>array("FriendController@destroy",$user->id)))}}
                                    {{ Form::hidden('_method', 'DELETE') }}
                                    <input type="submit" class="btn btn-xs btn-danger" value="Remove Friend">
                                    {{Form::close()}}
                                @else
                                    {{Form::open(array('action'=>"FriendController@store"))}}
                                    {{Form::hidden('friend_id', $user->id)}}
                                    <input type="submit" class="btn btn-xs btn-primary" value="Add Friend">
                                    {{Form::close()}}
                                @endif
                            @else
                                <p>This is you.</p>
                            @endif
                            @endif
                        </p>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
    </div>
@stop
@stop